services:
  
  boss:
    image: buzzobuono/waluigi-bossd:latest
    ports:
    - target: 8082
      published: 8082
      protocol: tcp
      mode: ingress
    environment:
      - WALUIGI_BOSS_DB_PATH=/db/waluigi.db
    command: ["wlbossd"]
    volumes:
      - ./db:/db
    deploy:
      replicas: 4

  worker:
    image: buzzobuono/waluigi-workerd:latest
    depends_on:
      - boss
    environment:
      - WALUIGI_WORKER_BOSS_URL=http://boss:8082
      - WALUIGI_WORKER_WORKDIR=/work
      - WALUIGI_WORKER_SLOTS=1
    volumes:
      - ./work:/work
      - ./source:/source
    deploy:
      replicas: 16