FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY ./waluigi /tmp/waluigi_src/waluigi
COPY ./pyproject.toml /tmp/waluigi_src/

RUN pip install /tmp/waluigi_src/

RUN rm -rf /tmp/waluigi_src

CMD ["wlbossd"]